-- Add visitor tracking table and seed baseline visits
create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

-- Enable RLS
alter table public.visits enable row level security;

-- Allow anonymous and authenticated users to record visits and read totals
create policy "Allow public read on visits"
  on public.visits
  for select
  to anon, authenticated
  using (true);

create policy "Allow public insert on visits"
  on public.visits
  for insert
  to anon, authenticated
  with check (true);

-- Seed 500 historical visits to avoid starting from zero
insert into public.visits (created_at)
select now() - (g * interval '1 minute')
from generate_series(1, 500) as g;
